// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_types.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createContentType = `-- name: CreateContentType :one
INSERT INTO content_types (id, name, slug, fields, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, fields, created_at, updated_at
`

type CreateContentTypeParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Fields    json.RawMessage `json:"fields"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) CreateContentType(ctx context.Context, arg CreateContentTypeParams) (ContentType, error) {
	row := q.db.QueryRow(ctx, createContentType,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Fields,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContentType = `-- name: DeleteContentType :exec
DELETE FROM content_types WHERE id = $1
`

func (q *Queries) DeleteContentType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContentType, id)
	return err
}

const getContentTypeByID = `-- name: GetContentTypeByID :one
SELECT id, name, slug, fields, created_at, updated_at
FROM content_types
WHERE id = $1
`

func (q *Queries) GetContentTypeByID(ctx context.Context, id uuid.UUID) (ContentType, error) {
	row := q.db.QueryRow(ctx, getContentTypeByID, id)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentTypeBySlug = `-- name: GetContentTypeBySlug :one
SELECT id, name, slug, fields, created_at, updated_at
FROM content_types
WHERE slug = $1
`

func (q *Queries) GetContentTypeBySlug(ctx context.Context, slug string) (ContentType, error) {
	row := q.db.QueryRow(ctx, getContentTypeBySlug, slug)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentTypes = `-- name: ListContentTypes :many
SELECT id, name, slug, fields, created_at, updated_at
FROM content_types
ORDER BY name
`

func (q *Queries) ListContentTypes(ctx context.Context) ([]ContentType, error) {
	rows, err := q.db.Query(ctx, listContentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentType{}
	for rows.Next() {
		var i ContentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Fields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentType = `-- name: UpdateContentType :exec
UPDATE content_types
SET name = $2, fields = $3, updated_at = $4
WHERE id = $1
`

type UpdateContentTypeParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Fields    json.RawMessage `json:"fields"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) error {
	_, err := q.db.Exec(ctx, updateContentType,
		arg.ID,
		arg.Name,
		arg.Fields,
		arg.UpdatedAt,
	)
	return err
}
