// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, content_type_id, title, slug, path, parent_id, author_id, status, fields, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
`

type CreateEntryParams struct {
	ID            uuid.UUID       `json:"id"`
	ContentTypeID uuid.UUID       `json:"content_type_id"`
	Title         string          `json:"title"`
	Slug          string          `json:"slug"`
	Path          string          `json:"path"`
	ParentID      pgtype.UUID     `json:"parent_id"`
	AuthorID      uuid.UUID       `json:"author_id"`
	Status        string          `json:"status"`
	Fields        json.RawMessage `json:"fields"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Title,
		arg.Slug,
		arg.Path,
		arg.ParentID,
		arg.AuthorID,
		arg.Status,
		arg.Fields,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Path,
		&i.ParentID,
		&i.AuthorID,
		&i.Status,
		&i.Fields,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
FROM entries
WHERE id = $1
`

func (q *Queries) GetEntryByID(ctx context.Context, id uuid.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Path,
		&i.ParentID,
		&i.AuthorID,
		&i.Status,
		&i.Fields,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryByPath = `-- name: GetEntryByPath :one
SELECT id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
FROM entries
WHERE path = $1 AND status = 'published'
`

func (q *Queries) GetEntryByPath(ctx context.Context, path string) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntryByPath, path)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Path,
		&i.ParentID,
		&i.AuthorID,
		&i.Status,
		&i.Fields,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryPath = `-- name: GetEntryPath :one
SELECT path FROM entries WHERE id = $1
`

func (q *Queries) GetEntryPath(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getEntryPath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getNavigationItems = `-- name: GetNavigationItems :many
SELECT id, title, slug, path, parent_id
FROM entries
WHERE status = 'published'
ORDER BY path
`

type GetNavigationItemsRow struct {
	ID       uuid.UUID   `json:"id"`
	Title    string      `json:"title"`
	Slug     string      `json:"slug"`
	Path     string      `json:"path"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetNavigationItems(ctx context.Context) ([]GetNavigationItemsRow, error) {
	rows, err := q.db.Query(ctx, getNavigationItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNavigationItemsRow{}
	for rows.Next() {
		var i GetNavigationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
FROM entries
ORDER BY created_at DESC
`

func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.ParentID,
			&i.AuthorID,
			&i.Status,
			&i.Fields,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByContentType = `-- name: ListEntriesByContentType :many
SELECT id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
FROM entries
WHERE content_type_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEntriesByContentType(ctx context.Context, contentTypeID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.ParentID,
			&i.AuthorID,
			&i.Status,
			&i.Fields,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByStatus = `-- name: ListEntriesByStatus :many
SELECT id, content_type_id, title, slug, path, parent_id, author_id, status, fields, published_at, created_at, updated_at
FROM entries
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEntriesByStatus(ctx context.Context, status string) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.ParentID,
			&i.AuthorID,
			&i.Status,
			&i.Fields,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEntry = `-- name: PublishEntry :exec
UPDATE entries
SET status = 'published', published_at = $2, updated_at = $3
WHERE id = $1
`

type PublishEntryParams struct {
	ID          uuid.UUID          `json:"id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) PublishEntry(ctx context.Context, arg PublishEntryParams) error {
	_, err := q.db.Exec(ctx, publishEntry, arg.ID, arg.PublishedAt, arg.UpdatedAt)
	return err
}

const unpublishEntry = `-- name: UnpublishEntry :exec
UPDATE entries
SET status = 'draft', published_at = NULL, updated_at = $2
WHERE id = $1
`

type UnpublishEntryParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UnpublishEntry(ctx context.Context, arg UnpublishEntryParams) error {
	_, err := q.db.Exec(ctx, unpublishEntry, arg.ID, arg.UpdatedAt)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET title = $2, slug = $3, path = $4, fields = $5, updated_at = $6
WHERE id = $1
`

type UpdateEntryParams struct {
	ID        uuid.UUID       `json:"id"`
	Title     string          `json:"title"`
	Slug      string          `json:"slug"`
	Path      string          `json:"path"`
	Fields    json.RawMessage `json:"fields"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.Exec(ctx, updateEntry,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Path,
		arg.Fields,
		arg.UpdatedAt,
	)
	return err
}
