// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (id, filename, mime_type, size, storage_path, uploader_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, filename, mime_type, size, storage_path, uploader_id, created_at
`

type CreateMediaFileParams struct {
	ID          uuid.UUID `json:"id"`
	Filename    string    `json:"filename"`
	MimeType    string    `json:"mime_type"`
	Size        int64     `json:"size"`
	StoragePath string    `json:"storage_path"`
	UploaderID  uuid.UUID `json:"uploader_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.ID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.StoragePath,
		arg.UploaderID,
		arg.CreatedAt,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.StoragePath,
		&i.UploaderID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE id = $1
`

func (q *Queries) DeleteMediaFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, id)
	return err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT id, filename, mime_type, size, storage_path, uploader_id, created_at
FROM media_files
WHERE id = $1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id uuid.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.StoragePath,
		&i.UploaderID,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaFiles = `-- name: ListMediaFiles :many
SELECT id, filename, mime_type, size, storage_path, uploader_id, created_at
FROM media_files
ORDER BY created_at DESC
`

func (q *Queries) ListMediaFiles(ctx context.Context) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.StoragePath,
			&i.UploaderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
