// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Fields    json.RawMessage `json:"fields"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Entry struct {
	ID            uuid.UUID          `json:"id"`
	ContentTypeID uuid.UUID          `json:"content_type_id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Path          string             `json:"path"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	AuthorID      uuid.UUID          `json:"author_id"`
	Status        string             `json:"status"`
	Fields        json.RawMessage    `json:"fields"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type EntryVersion struct {
	ID        uuid.UUID       `json:"id"`
	EntryID   uuid.UUID       `json:"entry_id"`
	Title     string          `json:"title"`
	Fields    json.RawMessage `json:"fields"`
	AuthorID  uuid.UUID       `json:"author_id"`
	CreatedAt time.Time       `json:"created_at"`
}

type MediaFile struct {
	ID          uuid.UUID `json:"id"`
	Filename    string    `json:"filename"`
	MimeType    string    `json:"mime_type"`
	Size        int64     `json:"size"`
	StoragePath string    `json:"storage_path"`
	UploaderID  uuid.UUID `json:"uploader_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
